Conceptual Question #3
A. The answer is iii because the difference between college and high school gradautes is found by the GPA, 35-10. When the GPA is larger than 3.5, the effect causes the advantage to change toward the high school graduates.

B. The predicted salary for a college graduate with an IQ of 110 and a 4.0 GPA is about $137,100. This result is found by: 50 + 20(4) + 0.07(110) + 35 + 0.01(4)(110) - 10(4)

C. False. A small interaction coefficient doesn't really result in the interaction effect being irrelevant. The importance is reliant on the scale of the variables and the statistical significance of the coefficient.

Applied Question #10

A. With the use of price, urban, and US a multiple regression model successfully predicted sales.

B. Interpretation =
Price demonstrated a negative significant relationship with sales. With a 1 unit increase in price, resulted in a decrease of about 0.0545 units in sales. Urban was not significantly significant, this demonstrated that urban location didn't affect sales in an important way. US remained statistically significant, the US had about 1.2 higher sales when compared to non-us stores.

C. The equation used: Sales = 13.0435 - 0.0545 (price) - 0.0219 (urban) + 1.2006 (US)

D. Price and US were significant in predicting (p< .001). Urban being insignificant (p = 0.936)

E. The reducted model eliminated urban and included price and US.

Reduced Model -

Sales = 13.0308 - 0.0545(P) + 1.1996(US)

F. The full and reduced models included almost identical R2 values (0.239), demonstrating that eliminating urban didn't decrease the performance of the model.

G. 95% intervals -
Price: (-0.0648, -0.0442)
US: (0.6915, 1.7078)

H. The diagnostic analysis demonstrated limited evidence of influential observations. There were no extreme outliers that were found throughout this analysis.

Model 1 Linear

In [ ]:
import pandas as pd

train = pd.read_csv("/train.csv")
test = pd.read_csv("/test.csv")

train.head()

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Separate predictors and target
X = train.drop("Rings", axis=1)
y = train["Rings"]

# Tell Python which column is categorical
categorical = ["Sex"]

# Convert Sex into numbers
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical)
    ],
    remainder="passthrough"
)

# Create model pipeline
from sklearn.pipeline import Pipeline

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regression", LinearRegression())
])

# Fit model
model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Sex'])])),
                ('regression', LinearRegression())])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Separate predictors and target
X = train.drop("Rings", axis=1)
y = train["Rings"]

# Categorical column
categorical = ["Sex"]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical)
    ],
    remainder="passthrough"
)

# Full model pipeline
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regression", LinearRegression())
])

# Train model
model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Sex'])])),
                ('regression', LinearRegression())])

In [27]:
predictions = model.predict(test)

# Remove negative predictions
predictions = predictions.clip(0)

In [28]:
submission = pd.DataFrame({
    "id": test["id"],
    "Rings": predictions
})

submission.to_csv("submission.csv", index=False)

submission.head()

      id      Rings
0  90615   8.511788
1  90616  10.006078
2  90617  10.282228
3  90618  10.932569
4  90619   7.759140

In [29]:
predictions.min()

np.float64(0.0)

Model 2 Random Forest

In [30]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [32]:
X = train.drop("Rings", axis=1)
y = train["Rings"]

In [33]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

categorical = ["Sex"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical)
    ],
    remainder="passthrough"
)

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("random_forest", RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ))
])

In [34]:
rf_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Sex'])])),
                ('random_forest',
                 RandomForestRegressor(n_estimators=200, random_state=42))])

In [35]:
rf_predictions = rf_model.predict(test)

rf_predictions[:10]

array([10.22 , 10.21 , 12.165, 11.4  ,  9.21 , 10.075, 11.28 ,  6.38 ,
        8.005, 12.225])

In [36]:
rf_predictions = rf_predictions.clip(0)

rf_predictions.min()

np.float64(3.35)

In [39]:
rf_submission = pd.DataFrame({
    "id": test["id"],
    "Rings": rf_predictions
})

rf_submission.to_csv("random_forest_submission.csv", index=False)

rf_submission.head()

      id   Rings
0  90615  10.220
1  90616  10.210
2  90617  12.165
3  90618  11.400
4  90619   9.210

Abalone Dataset Regression Outcome
Two regression mdels were created to predict abalone age.

Linear RegressionL:
Private Kaggle MSLE Score = 0.16499

Random Forest Regression:
Private Kaggle MSLE Score = 0.16813

The linear regression model preformed a little better because the resulted in a lower MSLE score. The random forest can model nonlinear relationships, didn't enhance prediction performance for this project.

In [ ]:
Questions

In [43]:
import pandas as pd
import statsmodels.api as sm

carseats = pd.read_csv("Carseats.csv")

carseats.head()

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No

In [45]:
import pandas as pd
import statsmodels.api as sm

# Load data
carseats = pd.read_csv("Carseats.csv")

# Select variables
X = carseats[['Price', 'Urban', 'US']]
y = carseats['Sales']

# Convert categorical variables to numbers
X = pd.get_dummies(X, drop_first=True)

# Make sure everything is numeric
X = X.astype(float)

# Add intercept
X = sm.add_constant(X)

# Fit regression
model = sm.OLS(y, X).fit()

# View results
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     41.52
Date:                Thu, 30 Jul 2026   Prob (F-statistic):           2.39e-23
Time:                        01:18:55   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1863.
Df Residuals:                     396   BIC:                             1879.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0435      0.651     20.036      0.000      11.764      14.323
Price         -0.0545      0.005    -10.389      0.000      -0.065      -0.044
Urban_Yes     -0.0219      0.272     -0.081      0.936      -0.556       0.512
US_Yes         1.2006      0.259      4.635      0.000       0.691       1.710
==============================================================================
Omnibus:                        0.676   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.713   Jarque-Bera (JB):                0.758
Skew:                           0.093   Prob(JB):                        0.684
Kurtosis:                       2.897   Cond. No.                         628.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [47]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     41.52
Date:                Thu, 30 Jul 2026   Prob (F-statistic):           2.39e-23
Time:                        01:21:14   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1863.
Df Residuals:                     396   BIC:                             1879.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0435      0.651     20.036      0.000      11.764      14.323
Price         -0.0545      0.005    -10.389      0.000      -0.065      -0.044
Urban_Yes     -0.0219      0.272     -0.081      0.936      -0.556       0.512
US_Yes         1.2006      0.259      4.635      0.000       0.691       1.710
==============================================================================
Omnibus:                        0.676   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.713   Jarque-Bera (JB):                0.758
Skew:                           0.093   Prob(JB):                        0.684
Kurtosis:                       2.897   Cond. No.                         628.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
# Smaller model using only Price and US

X2 = carseats[['Price', 'US']]
y = carseats['Sales']

# Convert US (Yes/No) into dummy variable
X2 = pd.get_dummies(X2, drop_first=True)

# Convert to numeric
X2 = X2.astype(float)

# Add intercept
X2 = sm.add_constant(X2)

# Fit smaller model
small_model = sm.OLS(y, X2).fit()

# Show results
small_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.235
Method:                 Least Squares   F-statistic:                     62.43
Date:                Thu, 30 Jul 2026   Prob (F-statistic):           2.66e-24
Time:                        01:23:35   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1861.
Df Residuals:                     397   BIC:                             1873.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0308      0.631     20.652      0.000      11.790      14.271
Price         -0.0545      0.005    -10.416      0.000      -0.065      -0.044
US_Yes         1.1996      0.258      4.641      0.000       0.692       1.708
==============================================================================
Omnibus:                        0.666   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.717   Jarque-Bera (JB):                0.749
Skew:                           0.092   Prob(JB):                        0.688
Kurtosis:                       2.895   Cond. No.                         607.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:
small_model.conf_int()

               0          1
const   11.79032  14.271265
Price   -0.06476  -0.044195
US_Yes   0.69152   1.707766

In [51]:
influence = small_model.get_influence()

influence.summary_frame()

,dfb_const,dfb_Price,dfb_US_Yes,cooks_d,standard_resid,hat_diag,dffits_internal,student_resid,dffits
0,-0.004685,0.004960,0.026900,0.000705,0.733148,0.003922,0.046002,0.732720,0.045975
1,0.041735,-0.044186,0.025407,0.001145,0.614748,0.009004,0.058597,0.614266,0.058551
2,0.005649,-0.005980,0.003187,0.000020,0.076422,0.009954,0.007663,0.076326,0.007653
3,-0.024934,0.026398,-0.024827,0.000745,-0.627878,0.005636,-0.047272,-0.627399,-0.047236
4,0.000424,-0.023159,0.053707,0.001602,-0.775599,0.007928,-0.069333,-0.775210,-0.069298
...,...,...,...,...,...,...,...,...,...
395,-0.048599,0.051453,0.077420,0.006908,2.156206,0.004438,0.143957,2.166210,0.144625
396,0.004026,-0.004263,-0.023118,0.000521,-0.630184,0.003922,-0.039541,-0.629705,-0.039511
397,-0.063661,0.067399,0.024032,0.002252,0.750194,0.011861,0.082190,0.749780,0.082145
398,-0.055414,0.058668,-0.050427,0.003226,-1.265274,0.006010,-0.098384,-1.266235,-0.098458
399,-0.005230,0.005538,0.030032,0.000879,0.818356,0.003922,0.051349,0.818015,0.051327

In [54]:
# Smaller model: Sales predicted by Price and US only

X_small = carseats[['Price', 'US']]
y = carseats['Sales']

# Convert US Yes/No into numbers
X_small = pd.get_dummies(X_small, drop_first=True)

# Force numeric values
X_small = X_small.astype(float)

# Add intercept
X_small = sm.add_constant(X_small)

# Fit smaller model
small_model = sm.OLS(y, X_small).fit()

small_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.235
Method:                 Least Squares   F-statistic:                     62.43
Date:                Thu, 30 Jul 2026   Prob (F-statistic):           2.66e-24
Time:                        01:30:26   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1861.
Df Residuals:                     397   BIC:                             1873.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0308      0.631     20.652      0.000      11.790      14.271
Price         -0.0545      0.005    -10.416      0.000      -0.065      -0.044
US_Yes         1.1996      0.258      4.641      0.000       0.692       1.708
==============================================================================
Omnibus:                        0.666   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.717   Jarque-Bera (JB):                0.749
Skew:                           0.092   Prob(JB):                        0.688
Kurtosis:                       2.895   Cond. No.                         607.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""